sudo: false

language: php

php:
    - 7.4

install:
    - make vendor/installed
    - wget -O phive.phar https://phar.io/releases/phive.phar
    - make tools/phpspec tools/phpunit tools/behat tools/readme-tester PHIVE_CMD="php phive.phar"

script:
    - tools/phpspec run --verbose
    - tools/phpunit
    - tools/behat
    - tools/readme-tester README.md
